name: alarms_pipeline
profile: alarms_pipeline

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  alarms_pipeline:
    staging:
      +materialized: view
      +schema: staging_dataset
    marts:
      +materialized: table
      +schema: analysis_dataset

seeds:
  alarms_pipeline:
    +schema: raw_dataset
    cities:
      +column_types:
        cityId: INT64
        population: INT64
        createdAt: TIMESTAMP
        updatedAt: TIMESTAMP