x-project-env: &project-env
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/secrets/service-account-key.json
  GCP_PROJECT_ID: ${GCP_PROJECT_ID}

x-project-volumes: &project-volumes
  - ./secrets:/opt/airflow/secrets:ro

services:
  postgres:
    ports:
      - "5432:5432"

  airflow-apiserver:
    environment:
      <<: *project-env
    volumes: *project-volumes

  airflow-scheduler:
    environment:
      <<: *project-env
    volumes: *project-volumes

  airflow-dag-processor:
    environment:
      <<: *project-env
    volumes: *project-volumes

  airflow-worker:
    environment:
      <<: *project-env
    volumes: *project-volumes

  airflow-triggerer:
    environment:
      <<: *project-env
    volumes: *project-volumes

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    env_file: .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/service-account-key.json
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
      - ./secrets:/app/secrets:ro
    restart: unless-stopped
